services:
  frontend:
    container_name: albuns-web
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
