server {
    listen 80;
    server_name albums.lrb.dev.br;

    root /var/www/albums-manager-web/dist;
    index index.html;

    location / {
        try_files $uri /index.html;  # ESSENCIAL para SPA
    }
}