name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            APP_DIR=/var/www/albums-manager-web
            OLD_CONTAINER=albuns-web
            NEW_CONTAINER=albuns-web-new
            OLD_PORT=8080
            NEW_PORT=8081

            cd $APP_DIR
            git pull origin main

            # build
            docker build -t albums-frontend:new .

            # garante que o novo container não existe
            docker rm -f $NEW_CONTAINER || true

            # sobe novo container
            docker run -d \
              --name $NEW_CONTAINER \
              -p $NEW_PORT:80 \
              albums-frontend:new

            # espera Nginx subir
            sleep 5

            # healthcheck REAL
            curl -f http://127.0.0.1:$NEW_PORT || exit 1

            # troca tráfego (host -> novo container)
            docker rm -f $OLD_CONTAINER || true

            docker run -d \
              --name $OLD_CONTAINER \
              --restart unless-stopped \
              -p $OLD_PORT:80 \
              albums-frontend:new

            # remove o temporário
            docker rm -f $NEW_CONTAINER