name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd /var/www/albums-manager-web

            git pull origin main

            docker stop albuns-web || true
            docker rm albuns-web || true

            docker build -t albums-frontend .

            docker run -d \
              --name albuns-web \
              --restart unless-stopped \
              -p 8080:80 \
              albums-frontend
